"""Add payment link to payments

Revision ID: 49c34ad0dbe6
Revises: c6fa40bc51b4
Create Date: 2026-09-21 23:06:18.419621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c34ad0dbe6'
down_revision: Union[str, Sequence[str], None] = 'c6fa40bc51b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_link')
    # ### end Alembic commands ###
