"""create buses table

Revision ID: a98e06e0c99e
Revises: d454d366a6e8
Create Date: 2026-09-16 23:21:25.014092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98e06e0c99e'
down_revision: Union[str, Sequence[str], None] = 'd454d366a6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('from_', sa.String(), nullable=False),
    sa.Column('to', sa.String(), nullable=False),
    sa.Column('departure', sa.String(), nullable=False),
    sa.Column('arrival', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buses_id'), 'buses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buses_id'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
