"""create ships table

Revision ID: da6756b6bff8
Revises: a98e06e0c99e
Create Date: 2026-09-17 00:08:00.631418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6756b6bff8'
down_revision: Union[str, Sequence[str], None] = 'a98e06e0c99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('from_', sa.String(), nullable=False),
    sa.Column('to', sa.String(), nullable=False),
    sa.Column('departure', sa.String(), nullable=False),
    sa.Column('arrival', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ships_id'), 'ships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ships_id'), table_name='ships')
    op.drop_table('ships')
    # ### end Alembic commands ###
